- name: Yolo Deployment
  hosts: all
  become: true
  vars:
    client_image: timaali/client:latest
    backend_image: timaali/backend:latest
    app_folder: /opt/yolo

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - docker-compose
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull Client Docker image
      community.docker.docker_image:
        name: "{{ client_image }}"
        source: pull

    - name: Pull Backend Docker image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: pull

    - name: Create app app_folder
      ansible.builtin.file:
        path: "{{ app_folder }}"
        state: directory

    - name: Copy docker-compose file
      template:
        src: ./../docker-compose.yml
        dest: "{{ app_folder }}/docker-compose.yml"

    - name: Copy backend folder
      template:
          src: ./../backend
          dest: "{{ app_folder }}/backend"

    - name: Start Containers
      shell: docker-compose up -d
      args:
        chdir: "{{ app_folder }}"
